version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: store_manager_db
    environment:
      POSTGRES_DB: tourdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 600060
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: store_manager_backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod

      DB_URL: jdbc:postgresql://postgres:5432/tourdb
      DB_USERNAME: postgres
      DB_PASSWORD: 600060

      JWT_SECRET: your-super-long-random-secret-at-least-32-bytes

volumes:
  postgres_data:
